// Shared case study data used across the site
export const CASE_STUDIES = [
  {
    id: 'apartment-gurgaon',
    title: '3BHK Apartment — Gurgaon',
    shortTitle: '3BHK Apartment — Gurgaon',
    type: 'Residential',
    typeSlug: 'residential',
    budget: '₹22 Lakhs',
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=900&q=80',
    outcome: 'Matched with the right brand in 7 days. Delivered on time and under budget.',
    challenge: 'A first-time homeowner had collected 8+ quotes — all with very different numbers. She had no idea what was fair or who to trust.',
    role: 'We sat down with her, understood the project, and told her what her budget could realistically get. We shortlisted 3 curated brands who specialise in compact luxury apartments.',
    fullOutcome: 'She got matched with the right brand in 7 days. Project delivered on time and 5% under budget.',
  },
  {
    id: 'coworking-noida',
    title: 'Co-Working Space — Noida Sector 62',
    shortTitle: 'Co-Working Space — Noida',
    type: 'Commercial',
    typeSlug: 'commercial',
    budget: '₹38 Lakhs',
    image: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=900&q=80',
    outcome: 'BOQ audit caught inflated rates. Client saved ₹6.8 Lakhs.',
    challenge: 'A startup founder had no prior experience with fit-outs. A contractor had already walked out mid-project, and he had a suspect quote in hand.',
    role: 'We audited the quote line by line and found rates were inflated by 18%. We then matched him with a commercial brand that could take over the project.',
    fullOutcome: 'He saved ₹6.8 Lakhs. The space was completed in 10 weeks.',
  },
  {
    id: 'hotel-lobby-hauz-khas',
    title: 'Hotel Lobby Redesign — Hauz Khas, Delhi',
    shortTitle: 'Hotel Lobby — Hauz Khas, Delhi',
    type: 'Hospitality',
    typeSlug: 'hospitality',
    budget: '₹35 Lakhs',
    image: 'https://media.base44.com/images/public/69bfb099e86c6c89f5403668/b8750c497_HotelLobby.jpg',
    outcome: 'Matched with a hospitality brand specialist. Redesign completed on budget.',
    challenge: "A hotel owner had a clear design vision but couldn't find brands experienced in hospitality that could work within a ₹35L budget.",
    role: 'We matched him with a boutique hospitality brand and helped structure a brief that balanced his design goals with the available budget.',
    fullOutcome: 'Lobby redesign done on budget. Guest satisfaction scores improved by 32%.',
  },
  {
    id: 'villa-greater-noida',
    title: 'Villa Renovation — Greater Noida',
    shortTitle: 'Villa Renovation — Greater Noida',
    type: 'Residential',
    typeSlug: 'residential',
    budget: '₹28 Lakhs',
    image: 'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=900&q=80',
    outcome: 'Project started within 2 weeks with full family alignment.',
    challenge: 'A family of five had conflicting opinions on the renovation. Everyone wanted something different. There was no clear direction to give any brand.',
    role: 'We facilitated a conversation, helped the family align on priorities, and built a single unified brief that everyone agreed on. Then we matched them with 2 relevant brands.',
    fullOutcome: 'Project started within 2 weeks. Full family alignment before a single brand visit.',
  },
];