// Static portfolio data — always available regardless of environment/backend connectivity
export const PROJECTS = [
  {
    id: '69c84f408e7923547ee5180e',
    slug: 'serene-3bhk-dlf-phase4',
    title: 'Serene 3BHK Apartment, DLF Phase 4',
    property_type: 'apartment',
    style: 'contemporary',
    city: 'Gurgaon',
    area_sqft: 1800,
    budget_utilized: '₹28 Lakhs',
    duration_weeks: 14,
    featured: true,
    partner_studio: 'Studio Aranya',
    partner_city: 'Gurgaon',
    partner_specialization: 'Residential interiors with a focus on calm, nature-inspired spaces.',
    cover_image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=900&q=80',
    before_image: 'https://images.unsplash.com/photo-1585412727339-54e4bae3bbf9?w=900&q=80',
    after_image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=900&q=80',
    gallery_images: [
      'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=800&q=80',
      'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80',
    ],
    brief: 'A family of four needed their 3BHK to feel spacious yet warm. They had two kids and wanted durable materials without compromising on aesthetics.',
    transformation: 'Studio Aranya opened up the living and dining zone by removing a non-load-bearing wall, added custom joinery throughout, and used a neutral palette with warm oak accents to create a cohesive, open feel.',
    client_quote: 'INTEXA saved us from picking the wrong studio. We almost went with someone who had no experience in family apartments. Studio Aranya was a perfect fit.',
  },
  {
    id: '69c84f408e7923547ee5180f',
    slug: 'minimal-luxury-penthouse-aerocity',
    title: 'Minimal Luxury Penthouse, Aerocity',
    property_type: 'penthouse',
    style: 'minimalist',
    city: 'Delhi',
    area_sqft: 3200,
    budget_utilized: '₹52 Lakhs',
    duration_weeks: 22,
    featured: true,
    partner_studio: 'De Stijl Collective',
    partner_city: 'Delhi',
    partner_specialization: 'High-end residential with expertise in minimalist luxury and bespoke finishes.',
    cover_image: 'https://images.unsplash.com/photo-1618219908412-a29a1bb7b86e?w=900&q=80',
    before_image: 'https://images.unsplash.com/photo-1502005229762-cf1b2da7c5d6?w=900&q=80',
    after_image: 'https://images.unsplash.com/photo-1618219908412-a29a1bb7b86e?w=900&q=80',
    gallery_images: [
      'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&q=80',
    ],
    brief: 'A senior executive wanted a penthouse that felt like a 5-star hotel — understated, sophisticated, and built to last 15+ years without looking dated.',
    transformation: 'De Stijl stripped back everything non-essential, installed book-matched marble walls in the living area, introduced floor-to-ceiling glazing, and curated Italian furniture that would stand the test of time.',
    client_quote: 'The INTEXA consultation helped us set the right brief before we even spoke to a studio. That clarity made everything smoother.',
  },
  {
    id: '69c84f408e7923547ee51810',
    slug: 'boutique-cafe-hauz-khas',
    title: 'Boutique Café Interiors, Hauz Khas',
    property_type: 'restaurant',
    style: 'eclectic',
    city: 'Delhi',
    area_sqft: 900,
    budget_utilized: '₹18 Lakhs',
    duration_weeks: 10,
    featured: false,
    partner_studio: 'Muse Studio',
    partner_city: 'Delhi',
    partner_specialization: 'Hospitality and F&B interiors with a distinct narrative-driven approach.',
    cover_image: 'https://media.base44.com/images/public/69bfb099e86c6c89f5403668/3352a4419_CafeInteriorsjpg.jpeg',
    before_image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=900&q=80',
    after_image: 'https://media.base44.com/images/public/69bfb099e86c6c89f5403668/3352a4419_CafeInteriorsjpg.jpeg',
    gallery_images: [
      'https://media.base44.com/images/public/69bfb099e86c6c89f5403668/3352a4419_CafeInteriorsjpg.jpeg',
    ],
    brief: 'A young restaurateur wanted a café in Hauz Khas that had a unique personality — not generic Scandi-minimalism but something rooted and layered.',
    transformation: 'Muse Studio built the concept around vintage Delhi — terrazzo floors, cane furniture, hand-painted murals referencing old Chandni Chowk, and antique brass fixtures.',
    client_quote: 'We had two quotes from studios before INTEXA — both were generic. Muse Studio completely understood what we wanted to say through this space.',
  },
  {
    id: '69c84f408e7923547ee51811',
    slug: 'modern-office-cyber-hub',
    title: 'Modern Corporate Office, Cyber Hub',
    property_type: 'office',
    style: 'modern',
    city: 'Gurgaon',
    area_sqft: 4500,
    budget_utilized: '₹65 Lakhs',
    duration_weeks: 18,
    featured: true,
    partner_studio: 'Axis Interior Works',
    partner_city: 'Gurgaon',
    partner_specialization: 'Commercial and corporate interiors with proven delivery on large floor plates.',
    cover_image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=900&q=80',
    before_image: 'https://images.unsplash.com/photo-1431540015161-0bf868a2d407?w=900&q=80',
    after_image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=900&q=80',
    gallery_images: [
      'https://images.unsplash.com/photo-1497366412874-3415097a27e7?w=800&q=80',
    ],
    brief: 'A 120-person tech company wanted their new office to reflect innovation while providing distinct zones for focus work, collaboration, and recreation.',
    transformation: 'Axis delivered a three-zone layout with biophilic breakout areas, a collaboration hub with movable walls, and private focus pods.',
    client_quote: "INTEXA's BOQ audit before we started saved us ₹4 Lakhs. And the studio they matched us with delivered on time.",
  },
  {
    id: '69c84f408e7923547ee51812',
    slug: 'heritage-villa-vasant-vihar',
    title: 'Heritage Villa Restoration, Vasant Vihar',
    property_type: 'villa',
    style: 'traditional',
    city: 'Delhi',
    area_sqft: 5500,
    budget_utilized: '₹95 Lakhs',
    duration_weeks: 30,
    featured: false,
    partner_studio: 'Vastu Collective',
    partner_city: 'Delhi',
    partner_specialization: 'Heritage and classical Indian residential — restoration and sensitive retrofitting.',
    cover_image: 'https://media.base44.com/images/public/69bfb099e86c6c89f5403668/424d3198e_HeritageVilla4.jpg',
    before_image: 'https://media.base44.com/images/public/69bfb099e86c6c89f5403668/979ab6fbd_home111594474956.jpg',
    after_image: 'https://media.base44.com/images/public/69bfb099e86c6c89f5403668/d34f1b575_HeritageVilla.jpg',
    gallery_images: [
      'https://media.base44.com/images/public/69bfb099e86c6c89f5403668/35a4f2b1c_HeritageVilla2.jpg',
      'https://media.base44.com/images/public/69bfb099e86c6c89f5403668/c7efc6ff8_heritagevilla3.jpg',
      'https://media.base44.com/images/public/69bfb099e86c6c89f5403668/6c6e80e07_HeriatageVilla6.jpg',
      'https://media.base44.com/images/public/69bfb099e86c6c89f5403668/c47d23ddc_HeritageVilla5.jpg',
    ],
    brief: 'An extended family wanted to restore their 40-year-old Vasant Vihar villa without losing its original character.',
    transformation: 'Vastu Collective restored original jaali work, sourced period-appropriate sandstone for flooring, upgraded all MEP while concealing modern systems behind traditional finishes.',
    client_quote: 'We interviewed 6 studios. None understood heritage sensitivity until INTEXA introduced us to Vastu Collective.',
  },
  {
    id: '69c84f408e7923547ee51813',
    slug: 'luxury-hotel-suites-aerocity',
    title: 'Luxury Hotel Suite Interiors, Aerocity',
    property_type: 'hotel',
    style: 'luxury',
    city: 'Delhi',
    area_sqft: 3600,
    budget_utilized: '₹1.2 Cr',
    duration_weeks: 20,
    featured: false,
    partner_studio: 'Grand Atelier',
    partner_city: 'Delhi',
    partner_specialization: 'Hospitality interiors for 5-star and boutique hotel brands across India.',
    cover_image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=900&q=80',
    before_image: null,
    after_image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=900&q=80',
    gallery_images: [],
    brief: 'A boutique hotel brand needed to redesign 8 suites to compete with 5-star brands nearby — within a tight per-key budget.',
    transformation: "Grand Atelier delivered a 'New Delhi Luxury' concept — locally sourced textiles, handcrafted brass hardware, and a palette of deep teals and warm ivory.",
    client_quote: 'INTEXA understood our cost constraints and matched us to a studio that had actually worked within hospitality budgets before.',
  },
];